FROM roboflow/tfjs-jetson
MAINTAINER Roboflow <docker@roboflow.com>

ENV ROBOFLOW_PACKAGE="roboflow-jetson"

RUN npm install pm2 -g

WORKDIR /
COPY ./ /inference-server/

# Install proper dependencies
WORKDIR /inference-server/server
RUN cp configs/package.jetson.json package.json
RUN npm install

ENTRYPOINT ["pm2-runtime", "pm2.config.js"]
