FROM roboflow/tfjs-jetson

RUN npm install pm2 -g

WORKDIR /
COPY ./ /inference-server/

# Install proper dependencies
WORKDIR /inference-server/server
RUN cp configs/package.jetson.json package.json
RUN npm install
