FROM roboflow/tfjs-jetson
MAINTAINER Roboflow <docker@roboflow.com>

ENV ROBOFLOW_PACKAGE="roboflow-jetson"
ENV TF_FORCE_GPU_ALLOW_GROWTH=true

WORKDIR /
COPY ./ /inference-server/

# Install proper dependencies
WORKDIR /inference-server/server
RUN npm install -g pm2 && \
    cp configs/package.jetson.json package.json && \
    npm install

ENTRYPOINT ["pm2-runtime", "pm2.config.js"]
